#app.jdbc.url=jdbc:mysql://192.168.0.107:3306/APDB
app.pageSize=2
#app.kafka.endpoint=192.168.0.107:10092

#app.persistence.packageToScan=com.autoparts
app.persistence.packageToScan=com.autoparts,com.autoparts.common.web.vo


#Atomikos
logging.level.com.atomikos=DEBUG

apdb.datasource.unique-resource-name=${spring.application.name}
apdb.datasource.max-pool-size=5
apdb.datasource.borrow-connection-timeout=30
apdb.datasource.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
apdb.datasource.xa-properties.user=apdbuser
apdb.datasource.xa-properties.password=QXV0b3BhcnRAMTgyMkF1dG9wYXJ0QDE4MjLOL1BSMtPbJS6+w5DFHRVieW51IJMoZSY=
apdb.datasource.xa-properties.pinGlobalTxToPhysicalConnection=true
#apdb.datasource.xa-properties.URL=jdbc:mysql://localhost:3306/APDB
apdb.datasource.xa-properties.URL=jdbc:mysql://192.168.0.10:3306/APDB
#apdb.datasource.xa-properties.URL=${app.jdbc.url}

