ap.persistence.packageToScan=com.autoparts,com.autoparts.common.web.vo

#spring.jta.enabled=false

#Atomikos
logging.level.com.atomikos=DEBUG
#
apdb.atomikos.datasource.unique-resource-name=${spring.application.name}
apdb.atomikos.datasource.max-pool-size=5
apdb.atomikos.datasource.borrow-connection-timeout=30
apdb.atomikos.datasource.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
apdb.atomikos.datasource.xa-properties.user=apdbuser
apdb.atomikos.datasource.xa-properties.password=QXV0b3BhcnRAMTgyMkF1dG9wYXJ0QDE4MjLOL1BSMtPbJS6+w5DFHRVieW51IJMoZSY=
#apdb.atomikos.datasource.xa-properties.password=p@ssw0rd
apdb.atomikos.datasource.xa-properties.pinGlobalTxToPhysicalConnection=true
apdb.atomikos.datasource.xa-properties.URL=jdbc:mysql://192.168.0.11:3306/APDB


#Hikari
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=true


# DataSource configuration
#spring.datasource
apdb.hikari.datasource.jdbc-url=jdbc:mysql://192.168.0.7:3306/APDB
apdb.hikari.datasource.username=apdbuser
apdb.hikari.datasource.password=QXV0b3BhcnRAMTgyMkF1dG9wYXJ0QDE4MjLOL1BSMtPbJS6+w5DFHRVieW51IJMoZSY=
apdb.hikari.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP connection pool settings
apdb.hikari.datasource.maximum-pool-size=10
apdb.hikari.datasource.minimum-idle=2
apdb.hikari.datasource.idle-timeout=30000
apdb.hikari.datasource.max-lifetime=1800000
apdb.hikari.datasource.connection-timeout=30000
#spring.datasource.hikari.pool-name=MyHikariPool
#spring.jpa.properties.hibernate.transaction.coordinator_class=jpa
apdb.hikari.datasource.connection-test-query: SELECT 1 FROM DUAL


#	Seata config
# Transaction service group (must match server-side configuration)
seata.enabled=true
seata.mode=AT
seata.tx-service-group=my_tx_group
seata.service.vgroup-mapping.my_tx_group=default
seata.service.grouplist.default=127.0.0.1:8091

seata.client.undo.log.table=undo_log

# Service vgroup mapping configuration
#seata.service.vgroup-mapping.my_tx_group=default

# Seata Registry configuration (using file-based registry or dynamic registry)
# file Or use "nacos", "zookeeper", etc.
#seata.registry.type=file
#seata.registry.file.grouplist=127.0.0.1:8091


# Disable Seata's global transaction manager if Atomikos is used
#seata.tx-service-group=your_tx_group
#seata.enable-auto-global-transaction=false  # Disable auto global transaction binding

#service.vgroupMapping.default_tx_group configuration item is required



#Cache implementation

#Caffeine
#spring.cache.type=caffeine
#spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=30s

#Redis
spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.password=your_password # (optional, if Redis requires authentication)
spring.redis.database=0
#spring.cache.redis.time-to-live=6000

# Connection pool settings
# Maximum number of connections
spring.redis.lettuce.pool.max-active=20         
spring.redis.lettuce.pool.max-idle=20        
spring.redis.lettuce.pool.min-idle=1         
spring.redis.lettuce.pool.max-wait=5000

ap.auth.uri.refresh=/ap/user/auth/v1/refresh
ap.auth.uri.login=/ap/user/auth/v1/login
ap.auth.uri.logout=/ap/user/auth/v1/logout
ap.auth.uri.permitted=/ap/maintenance/masterdata/v1/**,/ap/maintenance/companyprofile/v1/create

ap.web.internal-api-key=QXV0b3BhcnRAMTgyMkF1dG9wYXJ0QDE4MjLGDlNILobQINtfkRrrXFmZjfNkV1/zKES5R3mRJleocYYWhX0=


#ap.user.password-resetValidity

#	kafka
kafka.bootstrap-servers=192.168.0.11:10092

kafka.notificationEmail.topic=AP.NTF.MAIL
kafka.notificationEmail.consumer-concurrency=3
kafka.notificationEmail.groupId=GRP1

#kafka.rollbackCompanyProfile.topic=AP.ROLLBACK.CMPY
#kafka.rollbackCompanyProfile.consumer-concurrency=1
#kafka.rollbackCompanyProfile.groupId=GRP1



