ap.persistence.packageToScan=com.autoparts,com.autoparts.common.web.vo


#Atomikos
logging.level.com.atomikos=DEBUG

apdb.datasource.unique-resource-name=${spring.application.name}
apdb.datasource.max-pool-size=5
apdb.datasource.borrow-connection-timeout=30
apdb.datasource.xa-data-source-class-name=com.mysql.cj.jdbc.MysqlXADataSource
apdb.datasource.xa-properties.user=apdbuser
apdb.datasource.xa-properties.password=QXV0b3BhcnRAMTgyMkF1dG9wYXJ0QDE4MjLOL1BSMtPbJS6+w5DFHRVieW51IJMoZSY=
apdb.datasource.xa-properties.pinGlobalTxToPhysicalConnection=true
#apdb.datasource.xa-properties.URL=jdbc:mysql://localhost:3306/APDB
apdb.datasource.xa-properties.URL=jdbc:mysql://192.168.0.10:3306/APDB
#apdb.datasource.xa-properties.URL=${app.jdbc.url}

#spring.cache.type=caffeine
#spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=30s

spring.redis.host=localhost
spring.redis.port=6379
#spring.redis.password=your_password # (optional, if Redis requires authentication)
spring.redis.database=0
#spring.cache.redis.time-to-live=6000

# Connection pool settings
# Maximum number of connections
spring.redis.lettuce.pool.max-active=20         
spring.redis.lettuce.pool.max-idle=20        
spring.redis.lettuce.pool.min-idle=1         
spring.redis.lettuce.pool.max-wait=5000



ap.jwt.permitUri=\
/ap/maintenance/company/v1/get/**,\
/ap/maintenance/company/v1/getc/**,\
/ap/maintenance/company/v1/set/**

#	kafka
kafka.bootstrap-servers=192.168.0.10:10092

kafka.notificationEmail.topic=AP.NTF.MAIL
kafka.notificationEmail.consumer-concurrency=3
kafka.notificationEmail.groupId=GRP1

kafka.rollbackCompanyProfile.topic=AP.ROLLBACK.CMPY
kafka.rollbackCompanyProfile.consumer-concurrency=1
kafka.rollbackCompanyProfile.groupId=GRP1
