#	General status
status.success.code=0
status.success.message=Success

status.system_error.code=999
status.system_error.message=System Error. {}

status.user_session_expired.code=900
status.user_session_expired.message=Access denied. {}

status.fields_validation_error.code=901
status.fields_validation_error.message=Affected fields: {}

status.deserialize_exception.code=910
status.deserialize_exception.message=Deserialize validator exception. {}

status.mandatory_exception.code=911
status.mandatory_exception.message=Field: {} is mandatory

status.number_exception.code=912
status.number_exception.message=Field: {} is not a number

status.min_exception.code=913
status.min_exception.message=Field: {} value is smaller than min configure

status.max_exception.code=914
status.max_exception.message=Field: {} value is bigger than max configure 

status.regexp_exception.code=915
status.regexp_exception.message=Field: {} is not match to the regexp pattern

status.wrong_datetime_format.code=916
status.wrong_datetime_format.message=Field: {} is a invalid date-time format

status.internal_service_request_error.code=917
status.internal_service_request_error.message=Error from internal service request. {}

status.no_record_found.code=918
status.no_record_found.message=No record found. {}


#	User status 3XX
status.user_not_found.code=301
status.user_not_found.message=User not found

status.bad_credential.code=302
status.bad_credential.message=Bad Credential

status.reach_max_login_attempt.code=303
status.reach_max_login_attempt.message=Reach max login attempt

status.user_id_exist.code=304
status.user_id_exist.message=User ID exist

status.mismatch_password_policy.code=305
status.mismatch_password_policy.message=Password policy is not fulfill

status.user_pending_activate.code=306
status.user_pending_activate.message=This user is pending activation

status.invalid_user_status.code=307
status.invalid_user_status.message=Invalid user status. {}

status.password_reset_require.code=308
status.password_reset_require.message=User password is reset require
	
	
#	Company/Organization 1XX
#status.company_creation_error.code=100
#status.company_creation_error.message=Error while creating company. {}

status.company_not_found.code=101
status.company_not_found.message=Company not found

status.duplicate_brn.code=102
status.duplicate_brn.message=Duplicate Business Registration Number

status.company_duplicate_error.code=103
status.company_duplicate_error.message=This company is duplicated. {} {}



#	Product status 2XX
status.product_not_found.code=201
status.product_not_found.message=Product not found

#status.PRODUCT_GROUP_NOT_FOUND.code=250
#status.PRODUCT_GROUP_DELETE_CONSTRAINT.code=251
	