status.success.code=0
status.system_error.code=999

status.mandatory_exception.code=900
status.fields_validation_error.code=902
status.deserialize_validation_error.code=903

status.COMPANY_NOT_FOUND.code=100
status.COMPANY_BRN_DUPLICATE.code=101

status.user_not_found.code=XXX

status.product_not_found.code=200
status.PRODUCT_GROUP_NOT_FOUND.code=250
status.PRODUCT_GROUP_DELETE_CONSTRAINT.code=251