SELECT ROW_NUMBER() OVER() AS ROWNUM, CEIL(COUNT(u.ID) OVER()) AS TOTAL_RECORDS, :pageSize AS PAGE_SIZE,
u.ID, u.FIRST_NAME, u.MOBILE_NUM, u.EMAIL, u.COMPANY_ID, u.STATUS_ID AS STATUS
FROM T_USER u
WHERE u.COMPANY_ID = :companyId
AND u.IS_DEL = 'N'
ORDER BY u.FIRST_NAME
LIMIT :startRow, :pageSize
