SELECT ROW_NUMBER() OVER() AS ROWNUM, CEIL(COUNT(u.ID) OVER() / :pageSize) AS TOTAL_PAGE,,
u.ID, u.FIRST_NAME, u.MOBILE_NUM, u.EMAIL, u.COMPANY_ID, u.STATUS_ID
FROM T_USER u
WHERE u.COMPANY_ID = :companyId
AND u.IS_DEL = 'N'
ORDER BY u.FIRST_NAME
LIMIT :startRow, :pageSize
