UPDATE T_USER 
SET 
	UPDATED = :updated,
	UPDATED_BY = :updatedBy,
	MOBILE_NUM = CASE WHEN :mobileNumber IS NULL THEN MOBILE_NUM ELSE :mobileNumber END,
	FIRST_NAME = CASE WHEN :firstName IS NULL THEN FIRST_NAME ELSE :firstName END,
	LAST_NAME = CASE WHEN :lastName IS NULL THEN LAST_NAME ELSE :lastName END,
	EMAIL = CASE WHEN :email IS NULL THEN EMAIL ELSE :email END,
	/*COMPANY_ID = CASE WHEN :companyId IS NULL THEN COMPANY_ID ELSE :companyId END,*/
	STATUS_ID = CASE WHEN :statusId IS NULL THEN STATUS_ID ELSE :statusId END,
	IS_DEL = CASE WHEN :delete IS NULL THEN IS_DEL ELSE :delete END

WHERE ID = :id