SELECT u.ID, u.USER_ID, u.FIRST_NAME, u.LAST_NAME, u.MOBILE_NUM, u.EMAIL, u.COMPANY_ID, c.NAME AS COMPANY_NM, u.STATUS
FROM T_USER u
LEFT JOIN T_COMPANY c ON c.ID = u.COMPANY_ID
WHERE u.ID = :id 
AND u.IS_DEL = 'N'