#Springboot configuration
server.port=8081
server.shutdown=graceful

#management.endpoint.shutdown.enabled=true
#management.endpoint.info.enabled=true
#management.endpoints.web.exposure.include=info,shutdown
#management.security.enabled=false

#eureka config
#set false to disable eureka registration
spring.cloud.service-registry.auto-registration.enabled=false

spring.application.name=maintenance-service
eureka.instance.lease-renewal-interval-in-seconds=2
eureka.instance.lease-expiration-duration-in-seconds=2

eureka.instance.registryFetchIntervalSeconds=2

eureka.client.service-url.defaultZone=http://eureka-server:8080/eureka/
#eureka.client.service-url.defaultZone=http://localhost:9760/eureka/
eureka.client.register-with-eureka=true
#eureka.client.enabled=false 


#Application level configuration
ap.persistence.packageToScan=com.autoparts
ap.id=${spring.application.name}

#app.jwt.permitUri=/ap/maintenance/company/v1/ping,/ap/maintenance/user/v1/ping